export const SEARCH_CHATROOM_REQUEST = 'SEARCH_CHATROOM_REQUEST';
export const SEARCH_CHATROOM_SUCCESS = 'SEARCH_CHATROOM_SUCCESS';
export const SEARCH_CHATROOM_FAILURE = 'SEARCH_CHATROOM_FAILURE';

export const SEARCH_CHATS_REQUEST = 'SEARCH_CHATS_REQUEST';
export const SEARCH_CHATS_SUCCESS = 'SEARCH_CHATS_SUCCESS';
export const SEARCH_CHATS_FAILURE = 'SEARCH_CHATS_FAILURE';

export const LOAD_CHATROOM_REQUEST = 'LOAD_CHATROOM_REQUEST';
export const LOAD_CHATROOM_SUCCESS = 'LOAD_CHATROOM_SUCCESS';
export const LOAD_CHATROOM_FAILURE = 'LOAD_CHATROOM_FAILURE';

export const LOAD_CHATROOMS_REQUEST = 'LOAD_CHATROOMS_REQUEST';
export const LOAD_CHATROOMS_SUCCESS = 'LOAD_CHATROOMS_SUCCESS';
export const LOAD_CHATROOMS_FAILURE = 'LOAD_CHATROOMS_FAILURE';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';

export const INIT_CHATROOM_SEARCH_EXCEPT_CHATROOM_ID = 'INIT_CHATROOM_SEARCH_EXCEPT_CHATROOM_ID';
export const INIT_SEARCH_CHATS_EXCEPT_CHATROOM_ID = 'INIT_SEARCH_CHATS_EXCEPT_CHATROOM_ID';