export const SEARCH_CHATROOM_REQUEST = 'SEARCH_CHATROOM_REQUEST';
export const SEARCH_CHATROOM_SUCCESS = 'SEARCH_CHATROOM_SUCCESS';
export const SEARCH_CHATROOM_FAILURE = 'SEARCH_CHATROOM_FAILURE';

export const LOAD_CHATROOM_REQUEST = 'LOAD_CHATROOM_REQUEST';
export const LOAD_CHATROOM_SUCCESS = 'LOAD_CHATROOM_SUCCESS';
export const LOAD_CHATROOM_FAILURE = 'LOAD_CHATROOM_FAILURE';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';

export const INIT_CHATROOM_SEARCH_EXCEPT_CHATROOM_ID = 'INIT_CHATROOM_SEARCH_EXCEPT_CHATROOM_ID';